// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> greet() => RustLib.instance.api.crateApiGreet();

/// Scan a directory for markdown and text files
Future<List<String>> scanVault({required String path}) =>
    RustLib.instance.api.crateApiScanVault(path: path);

/// Read file content efficiently
Future<String> readFile({required String path}) =>
    RustLib.instance.api.crateApiReadFile(path: path);

/// Save file content
Future<void> saveFile({required String path, required String content}) =>
    RustLib.instance.api.crateApiSaveFile(path: path, content: content);

/// Search for text in files
Future<List<String>> searchVault(
        {required String vaultPath, required String query}) =>
    RustLib.instance.api
        .crateApiSearchVault(vaultPath: vaultPath, query: query);
